### ISSUE TITLE
Nimiq.watch API returns 50 results max

### ISSUE THREAD

**Issue by sisou** [svub/nimiq-voting-app#2]
No matter how much you set as the number of results you want to have, the maximum that is returned is 50. 

So if you increase the offset by 100, you miss 50 txs. 

https://github.com/svub/nimiq-voting-app/blob/bb2a73d87ae0cde03767ba599d5ecda7baa1012b/src/lib/network.ts#L33

**Comment by svub** [comment]
Ok, thanks for the pointer!!
Maybe add a note in the API doc if you like. :)
